baseURL = 'https://serjaii.github.io/Codigo-html-de-mi-pagina'
languageCode = 'es-es'
title = 'Serj AI'
theme = 'stack'

# Configuración del theme Stack
[params]
mainSections = ['post']
featuredImageField = 'image'
rssFullContent = true

[params.footer]
since = 2023

[params.dateFormat]
published = "02 Jan 2006"
lastUpdated = "02 Jan 2006 15:04 MST"

[params.sidebar]
emoji = "🤖"
subtitle = "Desarrollador y entusiasta de la IA"

[params.sidebar.avatar]
enabled = true
local = true
src = "img/mi-logo.jpg"

[params.article]
math = true
toc = true
readingTime = true

[params.widgets]
homepage = ["search", "archives", "categories", "tags"]
page = ["toc"]

[params.colorScheme]
toggle = true
default = "auto"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Inicio"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "Sobre Mi"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "projectos"
    name = "Proyectos"
    url = "/projectos/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "Archivo"
    url = "/archives/"
    weight = 4

  [[menu.main]]
    identifier = "search"
    name = "Buscar"
    url = "/search/"
    weight = 5

[[menu.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/serjaii"
